### ISSUE TITLE
Training with other datasets

### ISSUE THREAD

**Issue by rsjjdesj** [hzwer/arXiv2021-RIFE#148]
Has anyone trained RIFE_HDv2 with training set other than vimeo dataset: such as HD dataset. I

And were they able to get better visual quality for HD content.

**Comment by hzwer** [comment]
Hi, in fact I have tried some related experiments, indicating that the dataset itself is not important. If you want to improve the effect of the model at large resolutions, I recently found a very useful method https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123700477.pdf. In fact, I have used their method to solve this problem very well, and I should open source within two months.

**Comment by chiny92** [comment]
您可以共享另一组数据进行培训吗？当我在vimeo数据集上训练时，质量很好。但是当我训练其他数据集时，质量非常差。因此，如果您可以共享用于训练的其他数据集和用于生成这些训练集的脚本，那将非常有帮助

**Comment by hzwer** [comment]
@chiny92 我只尝试过一些自制数据集，我不了解 Vimeo90K 以外的插帧训练数据集
推荐在 vimeo90K 训练好的模型上进行微调

**Comment by chiny92** [comment]
> 我只尝试过一些自制数据集，我不了解 Vimeo90K 以外的插帧训练数据集
> 推荐在 vimeo90K 训练好的模型上进行微调

我也自己创建了一个三元组数据集。但是，当我在三元组数据集上进行训练时，推理结果非常差。在vimeo三胞胎上进行训练可获得良好的效果。因此，我不确定是否正确创建了三元组数据集。因此，我要求您共享其他数据集。或生成此类三元组数据集的脚本（似乎我做错了，推断结果很差）

**Comment by hzwer** [comment]
@chiny92 这个我确实没有办法提供帮助
建议你可视化一下你的数据集，也许其中没有处理好转场等问题？

**Comment by chiny92** [comment]
我检查了。数据集似乎没有问题。但是，当我训练时，与使用Vimeo数据集训练时相比，历元期间的损失通常要高得多。因此，我猜我在创建数据集时做错了什么。因为除了三元组图像外，我没有在训练中更改任何其他参数。因此，某些时期之后的损失应该在相似的范围内。但事实并非如此。因此，如果您可以共享对RIFE进行过培训的其他数据集，那么对我来说将非常有帮助。我可以调查一下，看看我在创建数据集时犯了什么错误。非常感谢您的帮助

**Comment by hzwer** [comment]
如果你提供几个你的数据，也许我可以研究一下；我确实没有办法向您提供数据，因为我已经很久没用 Vimeo 以外的数据集来训练模型了

**Comment by Chicke-ai** [comment]
我有一个非常疑惑的问题，就是三元组之外的ft0和ft1都是什么东西，可否提供数据预处理脚本文件

**Comment by hzwer** [comment]
> 我有一个非常疑惑的问题，就是三元组之外的ft0和ft1都是什么东西，可否提供数据预处理脚本文件

 需要生成光流 label，你可以用 raft 来生成

**Comment by YiWeiHuang-stack** [comment]
gt - i0生成ft0
gt - i1生成ft1

**Comment by YiWeiHuang-stack** [comment]
> 我有一个非常疑惑的问题，就是三元组之外的ft0和ft1都是什么东西，可否提供数据预处理脚本文件
gt - i0生成ft0
gt - i1生成ft1

**Comment by Chicke-ai** [comment]
您好我是北邮的学生，我们组对您的工作非常感兴趣，请问可以和您加一下微信详细聊聊么，或者以邮件的方式，关于您说的gt - i0的方式，好像并不能生成channel为2的样本呀，因为ft0不是channel为2的array嘛

**Comment by hzwer** [comment]
hzwer1999
