### ISSUE TITLE
question about hamming loss

### ISSUE THREAD

**Issue by btwbtm** [hzwer/arXiv2021-RIFE#158]
https://github.com/hzwer/arXiv2020-RIFE/blob/17a44899402ef04338ba47761748dba7120a1d77/model/loss.py#L43
To my understanding, the output of hamming loss is binary and itself is not differentiable. So this line is using average to approximate hamming loss?
Thx!

**Comment by hzwer** [comment]
Hello, in fact I'm not totally understand that, this code is refer to ARflow 
https://github.com/lliuz/ARFlow/blob/master/losses/loss_blocks.py#L34
It seems proposed by https://arxiv.org/abs/1711.07837
