### ISSUE TITLE
我看python 代码只能训练time=0.5的，想训练任意时间点模型RIFEm需要改哪些

### ISSUE THREAD

**Issue by ToBigboss** [hzwer/arXiv2021-RIFE#238]

**Comment by hzwer** [comment]
1. 把数据集换成 vimeo90K 7 帧数据集，每次随机 sample 三帧并附带时间戳，把数据接口理一下
2. 用 IFNet_m 替代 IFNet

**Comment by ToBigboss** [comment]
> 1. 把数据集换成 vimeo90K 7 帧数据集，每次随机 sample 三帧并附带时间戳，把数据接口理一下
> 2. 用 IFNet_m 替代 IFNet
> 
> 我们会在论文投稿结束后放出这部分训练和测试代码，目前实在是维护不过来

大佬，可以先把RIFEm的dataset.py发我邮箱么，非常感谢，eduyjj@163.com

**Comment by ToBigboss** [comment]
> 1. 把数据集换成 vimeo90K 7 帧数据集，每次随机 sample 三帧并附带时间戳，把数据接口理一下
> 2. 用 IFNet_m 替代 IFNet
> 
> 我们会在论文投稿结束后放出这部分训练和测试代码，目前实在是维护不过来

这样会取到同一张图片，有影响吗？  比如随机取出的三张图片是img1.png   img1.png   img2.png，，，这样的话时间戳timestep设置成0就行了吗？

**Comment by hzwer** [comment]
@ToBigboss 我最终代码是不重地取三张，但我印象中这两种写法影响非常微小

**Comment by ToBigboss** [comment]
> @ToBigboss 我最终代码是不重地取三张，但我印象中这两种写法影响非常微小

好的，，我现在是有重复图片的，，，已经在训练了，感觉loss下降很慢，，
timestep=0.5时，loss从4e-2下降到1e-2
timestep随机取时，loss从6e-2开始下降，，目前下降比较慢

**Comment by hzwer** [comment]
嗯，因为其实增加了任务难度，时间间隔也变长了
原来是连续三帧，现在跨了好多帧

**Comment by ToBigboss** [comment]
嗯，确实增加了学习难度。。
我想直接修改timestep=0.5模型出来的flow和mask，用来插帧其他时刻点，但是效果比较差。。
比如0.25时刻的flow和mask通过下面公式计算：
flow_0.25 = flow_0.5 x (0.25 / 0.5)
mask_0.25 = mask_0.5 x (0.25 / 0.5)

**Comment by ToBigboss** [comment]
> 对，直接这样做至少指标上会很差 请问你是要做研究还是要做应用呢

做应用，，想实现任意时间点插帧，，而不是2x    4x    8x这样的

**Comment by hzwer** [comment]
你可以先试试 https://github.com/hzwer/Practical-RIFE 的效果

**Comment by ToBigboss** [comment]
> 你可以先试试 https://github.com/hzwer/Practical-RIFE 的效果

好的  我看看

**Comment by ToBigboss** [comment]
> 对，直接这样做至少指标上会很差 请问你是要做研究还是要做应用呢

大佬，训练IFNet_m，loss最后降到多少呢？  我修改模型后，loss只降到4e-2，然后就下不去了

**Comment by hzwer** [comment]
https://github.com/hzwer/arXiv2021-RIFE/blob/main/benchmark/HD_multi_4X.py
可以用这个进行测试

**Comment by ToBigboss** [comment]
> https://github.com/hzwer/arXiv2021-RIFE/blob/main/benchmark/HD_multi_4X.py 可以用这个进行测试

训练IFNet_m模型的数据获取dataset代码片段如下：
` imgpaths = [imgpath + '/im1.png', imgpath + '/im2.png', imgpath + '/im3.png', imgpath + '/im4.png', imgpath + '/im5.png', imgpath + '/im6.png', imgpath + '/im7.png']
list = []
list.append(random.randint(0,6))
list.append(choice([i for i in range(0,7) if i not in [list[0]]]))
list.append(choice([i for i in range(0,7) if i not in [list[0], list[1]]]))
list.sort()
timestep = (list[1] - list[0]) * (1.0 / (list[2] - list[0]))`

图片和时间戳获取这么写的， 应该没问题把？

**Comment by hzwer** [comment]
@ToBigboss 是的，没问题

**Comment by ToBigboss** [comment]
> @ToBigboss 是的，没问题

但是train不收敛，我再排查下把

**Comment by hzwer** [comment]
不收敛的话，把蒸馏 loss 调成 1/5，感觉因为光流尺度变大了。

**Comment by ToBigboss** [comment]
> 

loss_G = loss_l1 + loss_tea + loss_distill * 0.2，，，改成这样吗

**Comment by hzwer** [comment]
嗯嗯

**Comment by ToBigboss** [comment]
> 嗯嗯

1.改成这样不行啊，，改成loss_distill * 0.2后，loss不降反而变大了，，训练20个epoch后loss从开始的7e-2变成1.5e-1了；
2.用原先得loss_distill * 0.01训练，loss能降到3e-2左右，，测试了一下在t=0.125，0.25，0.5上插出来的帧相差不太明显；

**Comment by hzwer** [comment]
@ToBigboss 不好意思我没注意细节，我的意思是改成 * 0.002

**Comment by ToBigboss** [comment]
> @ToBigboss 不好意思我没注意细节，我的意思是改成 * 0.002
效果还是不理想，，t=0.125，0.25，0.5的帧相差不太了，，4x慢速的话，视频一卡一卡的

**Comment by hzwer** [comment]
@ToBigboss 你确定你实现是对的吗，t=0 的时候能出 i0 吗

**Comment by ToBigboss** [comment]
> @ToBigboss 你确定你实现是对的吗，t=0 的时候能出 i0 吗

t=0不能得到i0.


我直接修改inference_img.py测试的，修改后的代码如下：
import os
import cv2
import torch
import argparse
from torch.nn import functional as F
import warnings
warnings.filterwarnings("ignore")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.set_grad_enabled(False)
if torch.cuda.is_available():
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = True

parser = argparse.ArgumentParser(description='Interpolation for a pair of images')
parser.add_argument('--img', dest='img', nargs=2, required=True)
parser.add_argument('--exp', default=4, type=int)
parser.add_argument('--ratio', default=0, type=float, help='inference ratio between two images with 0 - 1 range')
parser.add_argument('--rthreshold', default=0.02, type=float, help='returns image when actual ratio falls in given range threshold')
parser.add_argument('--rmaxcycles', default=8, type=int, help='limit max number of bisectional cycles')
parser.add_argument('--model', dest='modelDir', type=str, default='train_log', help='directory with trained model files')

args = parser.parse_args()
'''
try:
    try:
        from model.RIFE_HDv2 import Model
        model = Model()
        model.load_model(args.modelDir, -1)
        print("Loaded v2.x HD model.")
    except:
        from train_log.RIFE_HDv3 import Model
        model = Model()
        model.load_model(args.modelDir, -1)
        print("Loaded v3.x HD model.")
except:
    from model.RIFE_HD import Model
    model = Model()
    model.load_model(args.modelDir, -1)
    print("Loaded v1.x HD model")
model.eval()
model.device()
'''

from model.RIFE import Model
model = Model(arbitrary=True)
model.load_model(args.modelDir, -1)
model.eval()
model.device()

if args.img[0].endswith('.exr') and args.img[1].endswith('.exr'):
    img0 = cv2.imread(args.img[0], cv2.IMREAD_COLOR | cv2.IMREAD_ANYDEPTH)
    img1 = cv2.imread(args.img[1], cv2.IMREAD_COLOR | cv2.IMREAD_ANYDEPTH)
    img0 = (torch.tensor(img0.transpose(2, 0, 1)).to(device)).unsqueeze(0)
    img1 = (torch.tensor(img1.transpose(2, 0, 1)).to(device)).unsqueeze(0)

else:
    img0 = cv2.imread(args.img[0])
    img1 = cv2.imread(args.img[1])
    img0 = (torch.tensor(img0.transpose(2, 0, 1)).to(device) / 255.).unsqueeze(0)
    img1 = (torch.tensor(img1.transpose(2, 0, 1)).to(device) / 255.).unsqueeze(0)

n, c, h, w = img0.shape
ph = ((h - 1) // 32 + 1) * 32
pw = ((w - 1) // 32 + 1) * 32
padding = (0, pw - w, 0, ph - h)
img0 = F.pad(img0, padding)
img1 = F.pad(img1, padding)

if args.ratio:
    img_list = [img0]
    img0_ratio = 0.0
    img1_ratio = 1.0
    if args.ratio <= img0_ratio + args.rthreshold / 2:
        middle = img0
    elif args.ratio >= img1_ratio - args.rthreshold / 2:
        middle = img1
    else:
        tmp_img0 = img0
        tmp_img1 = img1
        for inference_cycle in range(args.rmaxcycles):
            middle = model.inference(tmp_img0, tmp_img1, timestep=0.5)
            middle_ratio = ( img0_ratio + img1_ratio ) / 2
            if args.ratio - (args.rthreshold / 2) <= middle_ratio <= args.ratio + (args.rthreshold / 2):
                break
            if args.ratio > middle_ratio:
                tmp_img0 = middle
                img0_ratio = middle_ratio
            else:
                tmp_img1 = middle
                img1_ratio = middle_ratio
    img_list.append(middle)
    img_list.append(img1)
else:
    img_list = [img0, img1]
    for i in range(args.exp):
        tmp = []
        for j in range(len(img_list) - 1):
            mid = model.inference(img_list[j], img_list[j + 1], timestep=0.125)
            tmp.append(img_list[j])
            tmp.append(mid)
        tmp.append(img1)
        img_list = tmp

if not os.path.exists('output'):
    os.mkdir('output')
for i in range(len(img_list)):
    if args.img[0].endswith('.exr') and args.img[1].endswith('.exr'):
        cv2.imwrite('output/img{}.exr'.format(i), (img_list[i][0]).cpu().numpy().transpose(1, 2, 0)[:h, :w], [cv2.IMWRITE_EXR_TYPE, cv2.IMWRITE_EXR_TYPE_HALF])
    else:
        cv2.imwrite('output/img{}.png'.format(i), (img_list[i][0] * 255).byte().cpu().numpy().transpose(1, 2, 0)[:h, :w])




训练代码修改了dataset.py和train.py和IFNet_m.py：

dataset.py只修改了getimg：
    def getimg(self, index):
        imgpath = os.path.join(self.image_root, self.meta_data[index])
        imgpaths = [imgpath + '/im1.png', imgpath + '/im2.png', imgpath + '/im3.png', imgpath + '/im4.png', imgpath + '/im5.png', imgpath + '/im6.png', imgpath + '/im7.png']
        #imgpaths = [imgpath + '/im1.png', imgpath + '/im2.png', imgpath + '/im3.png', imgpath + '/im4.png', imgpath + '/im5.png']

        # random 3 int number and sort and compute timestep
        list = []
        list.append(random.randint(0,6))
        list.append(choice([i for i in range(0,7) if i not in [list[0]]]))
        list.append(choice([i for i in range(0,7) if i not in [list[0], list[1]]]))
        #list.append(0)
        #list.append(4)
        #list.append(choice([i for i in range(0,5) if i not in [list[0], list[1]]]))
        #index = random.randint(0,2)
        #list.append(index+0)
        #list.append(index+1)
        #list.append(index+2)
        list.sort()
        timestep = (list[1] - list[0]) * (1.0 / (list[2] - list[0]))
            
        # Load images
        img0 = cv2.imread(imgpaths[list[0]])
        gt = cv2.imread(imgpaths[list[1]])
        img1 = cv2.imread(imgpaths[list[2]])
        return img0, gt, img1, timestep

IFNet_m.py只修改了如下代码：
        #timestep = (x[:, :1].clone() * 0 + 1) * timestep
        timestep = (x[:, :1].clone() * 0 + 1) * timestep.reshape(-1,1,1,1).float()

修改后的train.py如下：
import os
import cv2
import math
import time
import torch
import torch.distributed as dist
import numpy as np
import random
import argparse

from model.RIFE import Model
#from dataset import *
from dataset_m import *
from torch.utils.data import DataLoader, Dataset
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data.distributed import DistributedSampler

os.environ['CUDA_VISIBLE_DEVICES']="0,3"

device = torch.device("cuda")

log_path = 'train_log'

def get_learning_rate(step):
    if step < 2000:
        mul = step / 2000.
        return 3e-4 * mul
    else:
        mul = np.cos((step - 2000) / (args.epoch * args.step_per_epoch - 2000.) * math.pi) * 0.5 + 0.5
        return (3e-4 - 3e-5) * mul + 3e-5

def flow2rgb(flow_map_np):
    h, w, _ = flow_map_np.shape
    rgb_map = np.ones((h, w, 3)).astype(np.float32)
    normalized_flow_map = flow_map_np / (np.abs(flow_map_np).max())
    
    rgb_map[:, :, 0] += normalized_flow_map[:, :, 0]
    rgb_map[:, :, 1] -= 0.5 * (normalized_flow_map[:, :, 0] + normalized_flow_map[:, :, 1])
    rgb_map[:, :, 2] += normalized_flow_map[:, :, 1]
    return rgb_map.clip(0, 1)

def train(model, local_rank):
    if local_rank == 0:
        writer = SummaryWriter('train')
        writer_val = SummaryWriter('validate')
    step = 0
    nr_eval = 0
    dataset = VimeoDataset('train')
    sampler = DistributedSampler(dataset)
    train_data = DataLoader(dataset, batch_size=args.batch_size, num_workers=8, pin_memory=True, drop_last=True, sampler=sampler)
    args.step_per_epoch = train_data.__len__()
    dataset_val = VimeoDataset('validation')
    val_data = DataLoader(dataset_val, batch_size=16, pin_memory=True, num_workers=8)
    print('training...')
    time_stamp = time.time()
    for epoch in range(args.epoch):
        sampler.set_epoch(epoch)
        for i, (data, timestep) in enumerate(train_data):
        #for i, data in enumerate(train_data):
            data_time_interval = time.time() - time_stamp
            time_stamp = time.time()
            data_gpu = data.to(device, non_blocking=True) / 255.
            imgs = data_gpu[:, :6]
            gt = data_gpu[:, 6:9]
            learning_rate = get_learning_rate(step)
            #pred, info = model.update(imgs, gt, learning_rate, training=True)
            pred, info = model.update(imgs, gt, timestep, learning_rate, training=True)
            train_time_interval = time.time() - time_stamp
            time_stamp = time.time()
            if step % 200 == 1 and local_rank == 0:
                writer.add_scalar('learning_rate', learning_rate, step)
                writer.add_scalar('loss/l1', info['loss_l1'], step)
                writer.add_scalar('loss/tea', info['loss_tea'], step)
                writer.add_scalar('loss/distill', info['loss_distill'], step)
            if step % 1000 == 1 and local_rank == 0:
                gt = (gt.permute(0, 2, 3, 1).detach().cpu().numpy() * 255).astype('uint8')
                mask = (torch.cat((info['mask'], info['mask_tea']), 3).permute(0, 2, 3, 1).detach().cpu().numpy() * 255).astype('uint8')
                pred = (pred.permute(0, 2, 3, 1).detach().cpu().numpy() * 255).astype('uint8')
                merged_img = (info['merged_tea'].permute(0, 2, 3, 1).detach().cpu().numpy() * 255).astype('uint8')
                flow0 = info['flow'].permute(0, 2, 3, 1).detach().cpu().numpy()
                flow1 = info['flow_tea'].permute(0, 2, 3, 1).detach().cpu().numpy()
                for i in range(5):
                    imgs = np.concatenate((merged_img[i], pred[i], gt[i]), 1)[:, :, ::-1]
                    writer.add_image(str(i) + '/img', imgs, step, dataformats='HWC')
                    writer.add_image(str(i) + '/flow', np.concatenate((flow2rgb(flow0[i]), flow2rgb(flow1[i])), 1), step, dataformats='HWC')
                    writer.add_image(str(i) + '/mask', mask[i], step, dataformats='HWC')
                writer.flush()
            if local_rank == 0:
                print('epoch:{} {}/{} time:{:.2f}+{:.2f} loss_l1:{:.4e}'.format(epoch, i, args.step_per_epoch, data_time_interval, train_time_interval, info['loss_l1']))
            step += 1
        nr_eval += 1
        #f nr_eval % 5 == 0:
        #   evaluate(model, val_data, step, local_rank, writer_val)
        model.save_model(log_path, local_rank)    
        dist.barrier()

def evaluate(model, val_data, nr_eval, local_rank, writer_val):
    loss_l1_list = []
    loss_distill_list = []
    loss_tea_list = []
    psnr_list = []
    psnr_list_teacher = []
    time_stamp = time.time()
    for i, (data, timestep) in enumerate(val_data):
    #for i, data in enumerate(val_data):
        data_gpu = data.to(device, non_blocking=True) / 255.
        imgs = data_gpu[:, :6]
        gt = data_gpu[:, 6:9]
        with torch.no_grad():
            #pred, info = model.update(imgs, gt, training=False)
            pred, info = model.update(imgs, gt, timestep, training=False)
            merged_img = info['merged_tea']
        loss_l1_list.append(info['loss_l1'].cpu().numpy())
        loss_tea_list.append(info['loss_tea'].cpu().numpy())
        loss_distill_list.append(info['loss_distill'].cpu().numpy())
        for j in range(gt.shape[0]):
            psnr = -10 * math.log10(torch.mean((gt[j] - pred[j]) * (gt[j] - pred[j])).cpu().data)
            psnr_list.append(psnr)
            psnr = -10 * math.log10(torch.mean((merged_img[j] - gt[j]) * (merged_img[j] - gt[j])).cpu().data)
            psnr_list_teacher.append(psnr)
        gt = (gt.permute(0, 2, 3, 1).cpu().numpy() * 255).astype('uint8')
        pred = (pred.permute(0, 2, 3, 1).cpu().numpy() * 255).astype('uint8')
        merged_img = (merged_img.permute(0, 2, 3, 1).cpu().numpy() * 255).astype('uint8')
        flow0 = info['flow'].permute(0, 2, 3, 1).cpu().numpy()
        flow1 = info['flow_tea'].permute(0, 2, 3, 1).cpu().numpy()
        if i == 0 and local_rank == 0:
            for j in range(10):
                imgs = np.concatenate((merged_img[j], pred[j], gt[j]), 1)[:, :, ::-1]
                writer_val.add_image(str(j) + '/img', imgs.copy(), nr_eval, dataformats='HWC')
                writer_val.add_image(str(j) + '/flow', flow2rgb(flow0[j][:, :, ::-1]), nr_eval, dataformats='HWC')
    
    eval_time_interval = time.time() - time_stamp

    if local_rank != 0:
        return
    writer_val.add_scalar('psnr', np.array(psnr_list).mean(), nr_eval)
    writer_val.add_scalar('psnr_teacher', np.array(psnr_list_teacher).mean(), nr_eval)
        
if __name__ == "__main__":    
    parser = argparse.ArgumentParser()
    parser.add_argument('--epoch', default=300, type=int)
    parser.add_argument('--batch_size', default=16, type=int, help='minibatch size')
    parser.add_argument('--local_rank', default=0, type=int, help='local rank')
    parser.add_argument('--world_size', default=4, type=int, help='world size')
    args = parser.parse_args()
    torch.distributed.init_process_group(backend="nccl", world_size=args.world_size)
    torch.cuda.set_device(args.local_rank)
    seed = 1234
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True
    model = Model(args.local_rank, arbitrary=True)
    train(model, args.local_rank)

**Comment by ToBigboss** [comment]
> @ToBigboss 你确定你实现是对的吗，t=0 的时候能出 i0 吗

大佬，，能加qq或微信吗，，我qq/vx同号：707654930

**Comment by hzwer** [comment]
线下查明是增广 img0 和 img1 交换的时候，没有处理 1 - timestep

**Comment by hzwer** [comment]
> > https://github.com/hzwer/arXiv2021-RIFE/blob/main/benchmark/HD_multi_4X.py 可以用这个进行测试
> 
> 训练IFNet_m模型的数据获取dataset代码片段如下： imgpaths = [imgpath + '/im1.png', imgpath + '/im2.png', imgpath + '/im3.png', imgpath + '/im4.png', imgpath + '/im5.png', imgpath + '/im6.png', imgpath + '/im7.png'] list = [] list.append(random.randint(0,6)) list.append(choice([i for i in range(0,7) if i not in [list[0]]])) list.append(choice([i for i in range(0,7) if i not in [list[0], list[1]]])) list.sort() timestep = (list[1] - list[0]) * (1.0 / (list[2] - list[0]))
> 
> 图片和时间戳获取这么写的， 应该没问题把？
