### ISSUE TITLE
Where is RIFEm？

### ISSUE THREAD

**Issue by Zhang-Hu927** [hzwer/arXiv2021-RIFE#245]
Thanks a lot for improving a good work, in the Training strategy section of the paper it mentions using Vimeo90K-Septuplet to train RIFEm, but I didn't find RIFEm, is it IFNet_m? In IFNet_m, timestep is 0.5, not t = (n1 - n0)/(n2 - n0) as mentioned in the paper. Is it possible to provide the RIFEm？

**Comment by hzwer** [comment]
Hi, when training IFNet_m, you need to prepare training data with timestep=(n1 - n0)/(n2 - n0) using Vimeo90K-Septuplet. Other parts are basically unchanged.

Here is a snippet of the major modifications：https://github.com/hzwer/arXiv2021-RIFE/issues/238#issuecomment-1078706541

0.5 is just a default value of timestep, you can try to change it to see the results using pretrained RIFEm model.

**Comment by hzwer** [comment]
I merge some code of RIFEm to dataset.py and train.py.
