### ISSUE TITLE
梯度消失？

### ISSUE THREAD

**Issue by kyz20** [hzwer/arXiv2021-RIFE#247]
您好，我用您提供的源码直接训练，只是将分布式训练改成了单卡训练，其他任何代码没动，但是训练到5K step 左右的时候loss陡增，且后面loss一直没有下降的趋势，用tensorboard看images也都是错误的结果，插值帧全是一片空白，mask除了边缘也是空白，flow全是黄色

**Comment by hzwer** [comment]
你好，改成单卡训练后，最好把学习率调小，或者把 weight decay 调大
因为网络没有任何 normalization，大学习率确实会出现训炸的情况

**Comment by kyz20** [comment]
> 你好，改成单卡训练后，最好把学习率调小，或者把 weight decay 调大 因为网络没有任何 normalization，大学习率确实会出现训炸的情况
> 
> 我在这里改了一句话
> 
> https://github.com/hzwer/arXiv2021-RIFE/blob/dd941f3ae6f5f6ce7cd975fe058328f3682712a6/train.py#L63

你这改的代码不是卡越多，学习率越小吗？单卡的时候这样改学习率不就更大了吗？

**Comment by hzwer** [comment]
对不起我刚才可能没过脑子。。。
https://github.com/hzwer/arXiv2021-RIFE/blob/852112e47f3a14cf06f02fce95b6338a20c8ead4/train.py#L63

**Comment by YueChao-98** [comment]
> 你好，改成单卡训练后，最好把学习率调小，或者把 weight decay 调大 因为网络没有任何 normalization，大学习率确实会出现训炸的情况
> 
> 我在这里改了一句话 https://github.com/hzwer/arXiv2021-RIFE/blob/dd941f3ae6f5f6ce7cd975fe058328f3682712a6/train.py#L63

你好，想请问一下，为什么网络中不加入normalization呢？（例如batch norm或者instance norm）这有什么参考依据吗？是否跟光流有关。

**Comment by hzwer** [comment]
@YueChao-98 你好，单纯是因为加了以后会稍微降低性能，一直没找到正确方式

**Comment by YueChao-98** [comment]
> @YueChao-98 你好，单纯是因为加了以后会稍微降低性能，一直没找到正确方式

好的，谢谢你的回复。最近我在尝试基于RIFE做一些改进，发现修改后 网络在训练时对超参数非常敏感，容易出现nan。我看论文确实提到了BN会带来损失，但按照你的经验，是否加了normalization就能避免训练不稳定？

**Comment by hzwer** [comment]
@YueChao-98 会好一点，但是得不偿失，因为对齐最终性能会多出 20-40% 的推理开销
