### ISSUE TITLE
Can you release the training log of RIFE_m on vimeo90k-septuplet

### ISSUE THREAD

**Issue by Eric-chuan** [hzwer/arXiv2021-RIFE#249]
I've made some changes to RIFE_m, and retrained it. Could you release the train log to serve as a reference. Thank you very much.

**Comment by hzwer** [comment]
Yes. I upload it to https://drive.google.com/file/d/1v7KkQ-LhQliD0Mb0rbXYHZrc7R1UxwVj/view?usp=sharing

**Comment by Eric-chuan** [comment]
It would be very helpful to me, thanks.
