### ISSUE TITLE
HD数据集中有的帧是黑屏，可以忽略它们吗，这样也可以提高psnr

### ISSUE THREAD

**Issue by tianmaolin** [hzwer/arXiv2021-RIFE#250]
HD中720P的3段视频的前两帧都是黑屏，这样把第1帧的黑屏和第3帧的正常场景插帧，得到如下图
<img width="160" alt="IMAGE1" src="https://user-images.githubusercontent.com/30468336/164390930-031f4fbe-0336-4791-8fdc-f7253255e21d.png">
第1段视频的第1组插帧，上面是第1帧，下面是第3帧，中间是输出

第2帧gt和第1帧一样是黑屏，所以3个720P视频的第1个psnr都比较低：
HD720p_GT/parkrun_1280x720_50.yuv的前5个psnr：**22.35**, 27.66, 28.71, 28.57, 28.80
HD720p_GT/shields_1280x720_60.yuv'的前5个psnr：**23.52**, 36.97, 36.79, 36.78, 36.91
HD720p_GT/stockholm_1280x720_60.yuv的前5个psnr：**22.45**, 35.52, 35.52, 35.54, 35.51
HD1080p_GT/BlueSky.yuv的前5个psnr：41.00, 41.60, 41.73, 41.74, 42.11

感觉这3个psnr离群值都可以删掉，这样整个HD的psnr可以提高0.06
而且对黑屏插帧意义不大吧，就是一闪而过的画面，不需要把它考虑进psnr进行优化？

**Comment by hzwer** [comment]
目前主要只是用它来比一下相对的点，我沿用了 DAIN 给的代码所以没做改动
在我们业务数据集上，实际上会先有个过滤，把前后帧相关性较小的情况都去掉
我自己的经验是只有 Vimeo90K 的点是最扎实的，其它数据集的性能受到 trick 影响都挺大的

**Comment by tianmaolin** [comment]
谢谢解答，关于刷点说的很有道理
