### ISSUE TITLE
是否有C/C++开源版本？

### ISSUE THREAD

**Issue by JiadiLee** [hzwer/arXiv2021-RIFE#258]
大佬，我想咨询以下两个问题，感谢：
1. 当前是否有开源的C/C++的算法版本？耗时上应该会比python好一些吧
2. 我是通过C++调用inference_img.py 传递numpy数据进行图片插帧，python分析出来的结果imwrite 存本地正常，但是numpy 回传到C++上之后转Mat 展示感觉丢失了通道(如图片展示)，而回传到C++的原图转换是没问题的，是在python 算法分析时对图片做了一些转换操作么？
![image](https://user-images.githubusercontent.com/107230195/172978430-5a1dd9bd-acf8-4cb3-9372-4d6ad5e9dde1.png)

**Comment by hzwer** [comment]
😢 可是我不会写 c++

**Comment by JiadiLee** [comment]
> 😢 可是我不会写 c++

感谢大佬回复，后续我有时间再看一下，有进展的话会做一下同步
